import randomColor from "randomcolor";

export const colMap = {
  Hispanic: randomColor(),
  "First Nations": randomColor(),
  Black: randomColor(),
  White: randomColor(),
  European: randomColor(),
  "Middle Eastern": randomColor(),
  Male: randomColor(),
  Female: randomColor(),
  "Non-binary": randomColor(),
  Asian: randomColor(),
  "LGBTQ+": randomColor(),
  Disability: randomColor(),
  "Age < 18": randomColor(),
  "18 < Age < 30": randomColor(),
  "30 < Age < 50": randomColor(),
  "50 < Age < 70": randomColor(),
  "Age 70+": randomColor(),
  Christian: randomColor(),
  Muslim: randomColor(),
  Hindu: randomColor(),
  Buddhist: randomColor(),
  Atheist: randomColor(),
  Jewish: randomColor(),
  Sikh: randomColor(),
  Other: randomColor(),
};
